### ISSUE TITLE
Conventions / Design of config.yml

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/cli#131]
We should document the conventions used when writing a `_config.yml` file in more detail. There was some discussion in PR #73 around specifying `latex` options to see if we should have options for `cli` and `passed through to sphinx` as separate sections. 

One suggestion from @choldgraf is:

```yaml
latex:
  ourcustomoption1: val1
  config:
    passthroughkey: passthroughval
```

an alternative is to use a flatter structure

```yaml
latex:
  ourcustomoption1: val1
  passthroughkey: passthroughval
```

and filter the options to passthrough to `sphinx`.

In PR #73 I have adopted a nesting structure for `latex_documents` (https://github.com/ExecutableBookProject/cli/blob/d15726d18ae483bc70a55d9d64e7615ad3bf6a01/jupyter_book/book_template/_config.yml#L7) and my worry would be too many nested structures makes writing config hard. 

My thoughts are we should have a global config section for `latex` and filter the `sphinx` keys and pass them through to sphinx. (i.e. https://www.sphinx-doc.org/en/master/usage/configuration.html#latex-options)

**Comment by chrisjsewell** [comment]
Related note: There should most probably be a jsonschema for _config.yaml, which should be tested against when loading it

**Comment by choldgraf** [comment]
For the config structure, I guess the question is whether it's ok for us to have a single level of options where some of them are pass throughs, and others are treated special by jupyter book 

Re: a schema, yep, see https://github.com/ExecutableBookProject/cli/issues/53

**Comment by mmcky** [comment]
thanks @choldgraf sorry I missed the other issue - thanks for linking the two. 
Once structure is decided we can close this issue.

**Comment by choldgraf** [comment]
So I guess the decision is between:

For builder-specific configuration (`html`, `latex`, or the `sphinx` special-case) do we use config like this:

```
html:
  specialkey1: val1
  config:
    passthroughkey1: val1
```

or 

```
html:
  specialkey1: val1
  passthroughkey1: val1
```

with documentation that says "keys not in `<list of special keys>` will be passed directly to `<build configuration>`
