### ISSUE TITLE
Discuss nomenclature for `toc.yml`

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#32]
Right now, our table of contents uses the following structure:

```
- file: path/to/file
  pages:
  - file: path/to/subfile
  - file: path/to/subfile
```

The use of `file` and `pages` is semi-arbitrary right now. Is it a good choice? Do people have suggestions for other outputs?

A second question is how we want people to include more information than this in their books. For example, a page name can be given like so:

```
- file: path/to/file
  name: My name
```

and `My name` will over-ride the title of the page when it's displayed in the sidebar. Is it fine to add this extra metadata as `key: vals` in each TOC item?

**Comment by choldgraf** [comment]
cc @gregcaporaso who said he might have thoughts on this, and @jstac who has provided some feedback on this topic before

**Comment by jstac** [comment]
Ah, you beat me to it -- see #33.  Would you mind to merge?

**Comment by choldgraf** [comment]
@jstac sure thing - shall we close this one or 33?

**Comment by jstac** [comment]
I'll close #33.  Here's the main thing I wanted to say:

Do we want to move to a genuine "book-like" structure?  Rough example:

```yaml
- intro: a_file_with_book_title_and_preface
    chapter: a_file_containing_title_and_intro_to_chapter_1
        section: a_file_containing_intro_to_section_1
            - content: file_with_some_content
            - content: file_with_some_content
        section: a_file_containing_intro_to_section_2
            - content: file_with_some_content
            - content: file_with_some_content
    chapter: etc_etc
````
