### ISSUE TITLE
Appropriate names / structure for items in toc file --- discuss

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#33]
Currently the toc looks as follows with `file` and `pages`:

```yaml
- file: intro
- file: guide/01_overview
  pages:
  - file: guide/02_create
  - file: guide/03_build
  - file: guide/04_publish
  - file: guide/05_faq
  - file: guide/06_advanced
```

I suggested `pages` to draw on the "webpage" analogy but I'm not sure now that it was a good idea.  As @gregcaporaso said, `subsections` might be better because there's an obvious hierarchy.

One question is: do we want to move to a genuine "book-like" structure?  Rough example:

```yaml
- intro: a_file_with_book_title_and_preface
    chapter: a_file_containing_title_and_intro_to_chapter_1
        section: a_file_containing_intro_to_section_1
            - content: file_with_some_content
            - content: file_with_some_content
        section: a_file_containing_intro_to_section_2
            - content: file_with_some_content
            - content: file_with_some_content
    chapter: etc_etc
````
